### PR TITLE
Create todo list

### PR DESCRIPTION
**Pull request by thecodechaser**
This branch includes the following features:
Created todo list.
Users can select completed items.
Users can add items to todo list
Users can delete items from todo list
Users can delete all completed items.

### CODE REVIEW

**Comment by Gbengacode** [comment]
Weldone Codechaser on your project. 

You're doing great! 👏 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

## Happy coding and stay awesome! 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!


`  const clearElement = document.createElement('p');
  clearElement.className = 'clear';
  clearElement.innerText = 'Clear all completed';
[optional] It thinks it is a best practice that you use a button or a link to perform an action as paragraph tag is just to render a block of text

**Comment by thecodechaser** [comment]
> Weldone Codechaser on your project.
> 
> You're doing great! 👏
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> ## Happy coding and stay awesome! 🚀
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!
> 
> ` const clearElement = document.createElement('p'); clearElement.className = 'clear'; clearElement.innerText = 'Clear all completed'; [optional] It thinks it is a best practice that you use a button or a link to perform an action as paragraph tag is just to render a block of text

Hello, @Gbengacode 

Thank you for your code-review and feedback, I will work on the changes suggested by you to improve my project

**Review by Gbengacode — APPROVED** [review]
Good job. Congratulation, you can now merge your pull request

**Comment by thecodechaser** [comment]
> Good job. Congratulation, you can now merge your pull request

Hello, @Gbengacode 👋 
Thank you for approving the Pull Request.

**Pull request merged**
